Repository FE9-2/workroot, pull requests merged in 2024-12, with the labels that each got.

#81 Design: Card Board, comment ui(수정)
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/board/Comment.tsx
  tailwind.config.ts
Labels: 🎨 Design

#86 react-intersection-observer 라이브러리 추가 및 무한스크롤 적용 등
  package-lock.json
  package.json
  src/app/(pages)/mypage/comments/page.tsx
  src/app/(pages)/mypage/components/FilterBar/SortSection.tsx
  src/app/(pages)/mypage/components/FilterBar/TabMenu.tsx
  src/app/(pages)/mypage/components/FilterBar/constants.ts
  src/app/(pages)/mypage/components/FilterBar/index.tsx
  src/app/(pages)/mypage/components/MyPageContent.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/mypage/layout.tsx
  src/app/(pages)/mypage/page.tsx
  src/app/(pages)/mypage/posts/page.tsx
  src/app/(pages)/mypage/scrap/page.tsx
  src/app/components/button/dropdown/FilterDropdown.tsx
  src/app/components/layout/mypage/FilterBar.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/stories/design-system/components/dropdown/FilterDropdown.stories.tsx
  src/hooks/useUser.ts
  src/utils/recruitDateFommatter.ts
Labels: ✨ Feat, 🎨 Design

#87 로그인한 유저가 login, signup 페이지로 이동시 홈으로 강제 리다이렉트 등
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/mypage/layout.tsx
  src/app/components/layout/Header.tsx
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/middleware.ts
  src/store/userStore.ts
Labels: 📦️ Chore, 🔨 Refactor, 🎨 Design

#88 feat: oauth 카카오 간편 로그인 user 정보 불러오기
  public/icons/social/social_google.svg
  public/icons/social/social_kakao.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/oauth/apps/route.ts
  src/app/api/oauth/callback/kakao/route.ts
  src/app/components/card/cardList/RecruitCondition.tsx
  src/app/stories/design-system/components/card/cardList/RecruitCondition.stories.tsx
  src/app/stories/design-system/components/card/cardList/SubmitContCard.stories.tsx
Labels: ✨ Feat

#89 refactor: 회원가입 페이지 분리 및 관련 리팩토링
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(pages)/mypage/components/FilterBar/TabMenu.tsx
  src/app/(pages)/mypage/components/FilterBar/index.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/components/layout/Header.tsx
  src/app/components/modal/modals/confirm/CustomFormModal.tsx
  src/app/stories/design-system/components/modal/confirm/CustomFormModal.stories.tsx
  src/hooks/useAuth.ts
  src/middleware.ts
  src/types/modal.d.ts
Labels: 📦️ Chore, 🔨 Refactor, 🎨 Style

#90 refactor: 마이페이지 회원정보(지원자, 사장님) 수정 이미지 업로드 연동 등
  next.config.mjs
  public/android-icon-192x192.png
  public/apple-icon-180x180.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/site.webmanifest
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(home)/page.tsx
  src/app/(pages)/mypage/components/FilterBar/index.tsx
  src/app/api/(file)/images/upload/route.ts
  src/app/api/auth/refresh/route.ts
  src/app/api/users/me/route.ts
  src/app/components/button/dropdown/KebabDropdown.tsx
  src/app/components/layout/Header.tsx
  src/app/components/modal/modals/form/ChangePasswordModal.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/app/metadata.ts
  src/app/stories/design-system/components/dropdown/KebabDropdown.stories.tsx
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/middleware.ts
Labels: ✨ Feat, 🔨 Refactor, ⚙️ Setting

#93 fix: ChangePasswordModal 스토리북 관련 버그 수정
  .storybook/preview.tsx
  src/app/stories/design-system/components/modal/form/ChangePasswordModal.stories.tsx
Labels: 🐞 Fix

#91 Design : 알바폼 페이지
  package-lock.json
  src/app/(pages)/(addform)/addform/page.tsx
  src/app/(pages)/(addform)/addform/sections/RecruitCondition.tsx
  src/app/(pages)/(addform)/addform/sections/RecruitContent.tsx
  src/app/(pages)/(addform)/addform/sections/WorkCondition.tsx
  src/app/(pages)/(addform)/apply/[formId]/layout.tsx
  src/app/(pages)/(addform)/apply/[formId]/page.tsx
  src/app/(pages)/(addform)/component/Label.tsx
  src/app/(pages)/(addform)/layout.tsx
  src/app/api/(file)/images/upload/route.ts
  src/app/api/(file)/resume/upload/route.ts
  src/app/api/forms/route.ts
  src/app/components/button/default/CheckBtn.tsx
  src/app/components/button/dropdown/FilterDropdown.tsx
  src/app/components/button/dropdown/InputDropdown.tsx
  src/app/components/button/dropdown/TabMenuDropdown.tsx
  src/app/components/button/dropdown/TopMenuDropdown.tsx
  src/app/components/button/dropdown/dropdownComponent/DropdownList.tsx
  src/app/components/input/dateTimeDaypicker/DatePickerInput.tsx
  src/app/components/input/file/BaseFileInput.tsx
  src/app/components/input/file/DownloadInput.tsx
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/components/input/file/UploadInput.tsx
  src/app/components/input/text/LocationInput.tsx
  src/app/components/input/textarea/BaseTextArea.tsx
  src/app/components/layout/addFormLayout/AddFormLayout.tsx
  src/app/components/layout/addFormLayout/ApplyHeader.tsx
  src/app/stories/design-system/components/dropdown/InputDropdownBtn.stories.tsx
  src/app/stories/design-system/components/dropdown/TabMenuDropdown.stories.tsx
  src/app/stories/design-system/components/dropdown/TopMenuDropdown.stories.tsx
  src/app/stories/design-system/components/input/image/ImageInput.stories.tsx
  src/hooks/useWidth.ts
  src/types/addform.d.ts
  src/types/textInput.d.ts
Labels: 🎨 Design

#92 feat: 구글 간편로그인 구글서버에서 user 정보 받기
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/oauth/callback/google/route.ts
  src/app/api/oauth/callback/kakao/route.ts
  src/middleware.ts
  src/types/oauth/oauthReq.ts
Labels: ✨ Feat

#94 user 정보 localStorage 대신 react query 활용 등
  src/app/api/(file)/resume/upload/route.ts
  src/app/api/users/me/route.ts
  src/app/components/input/file/ImageInput/ImageInputwithPlaceHolder.tsx
  src/app/components/layout/Header.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/app/stories/design-system/components/input/picker/DatePicker.stories.tsx
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/middleware.ts
Labels: 🐞 Fix, 🔨 Refactor

#98 Feat: 카카오 API 호출을 통해 인가코드를 사용하는 로직제거
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/api/oauth/callback/google/route.ts
  src/app/api/oauth/callback/kakao/route.ts
Labels: ✨ Feat, 🐞 Fix, 📬 API

#101 feat: mypage 스크랩 필터 관련 기능 추가
  src/app/(pages)/mypage/components/FilterBar/SortSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/mypage/layout.tsx
  src/app/api/users/me/scrap/route.ts
  src/constants/filterOptions.ts
  src/store/filterStore.ts
Labels: ✨ Feat

#102 Feat: OAuth 간편 구글/카카오 회원가입/로그인 구현 완료
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/api/oauth/callback/google/route.ts
  src/app/api/oauth/callback/kakao/route.ts
  src/app/api/oauth/login/[provider]/route.ts
  src/types/oauth/oauth.d.ts
  src/types/oauth/oauthReq.ts
  tsconfig.json
Labels: ✨ Feat, 🐞 Fix, 📬 API

#110 feat: 검색 섹션 추가 및 스토리북 반영
  src/app/(pages)/albaList/components/SearchSection.tsx
  src/app/(pages)/albaList/page.tsx
  src/app/components/input/text/SearchInput.tsx
  src/app/stories/design-system/components/SearchSection.tsx
  src/app/stories/design-system/components/input/text/SearchInput.stories.tsx
  src/app/stories/design-system/components/layout/Header.tsx
  src/app/stories/design-system/pages/albaList/page.stories.tsx
  src/app/stories/design-system/pages/albaList/page.tsx
Labels: ✨ Feat

#111 Feat: 알바폼 생성 페이지 (사장님)
  src/app/(pages)/(addform)/addform/page.tsx
  src/app/(pages)/(addform)/addform/sections/RecruitCondition.tsx
  src/app/(pages)/(addform)/addform/sections/RecruitContent.tsx
  src/app/(pages)/(addform)/addform/sections/WorkCondition.tsx
  src/app/(pages)/(addform)/layout.tsx
  src/app/(pages)/(albaform)/Label.tsx
  src/app/(pages)/(albaform)/addform/RecruitCondition.tsx
  src/app/(pages)/(albaform)/addform/RecruitContent.tsx
  src/app/(pages)/(albaform)/addform/WorkCondition.tsx
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/apply/[formId]/page.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/api/forms/[formId]/applications/route.ts
  src/app/api/forms/route.ts
  src/app/api/oauth/login/[provider]/route.ts
  src/app/components/button/default/CheckBtn.tsx
  src/app/components/button/dropdown/InputDropdown.tsx
  src/app/components/button/dropdown/dropdownComponent/DropdownList.tsx
  src/app/components/input/applicantCountInput/ApplicantCountInput.tsx
  src/app/components/input/dateTimeDaypicker/DatePickerInput.tsx
  src/app/components/input/dateTimeDaypicker/DayPickerList.tsx
  src/app/components/input/dateTimeDaypicker/TimePickerInput.tsx
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/components/input/text/LocationInput.tsx
  src/app/components/layout/addFormLayout/AddFormLayout.tsx
  src/app/stories/design-system/components/dropdown/InputDropdownBtn.stories.tsx
  src/app/stories/design-system/components/input/file/Upload.stories.tsx
  src/app/stories/design-system/components/input/image/ImageInput.stories.tsx
  src/app/stories/design-system/components/input/picker/DatePicker.stories.tsx
  src/app/stories/design-system/components/input/picker/DayPicker.stories.tsx
  src/hooks/queries/user/me/useUpdateProfile.ts
  src/types/addform.d.ts
  tsconfig.json
Labels: ⚙ Build, 📬 API

#112 fix: 이미지 URL 및 날짜 검증 로직 추가
  src/app/(pages)/albaList/components/SearchSection.tsx
  src/app/(pages)/albaList/layout.tsx
  src/app/(pages)/albaList/page.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/ScrapListItem.tsx
  src/app/components/chip/Chip.tsx
  src/app/stories/design-system/pages/albaList/page.tsx
  src/constants/config.ts
  src/utils/workDayFormatter.ts
Labels: 🐞 Fix

#114 Chore : 알바폼 페이지 일부 수정
  src/app/(pages)/(albaform)/addform/RecruitConditionSection.tsx
  src/app/(pages)/(albaform)/addform/RecruitContentSection.tsx
  src/app/(pages)/(albaform)/addform/WorkConditionSection.tsx
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/api/forms/[formId]/applications/route.ts
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/components/layout/addFormLayout/ApplyHeader.tsx
Labels: 📦️ Chore

#115 Feat: 알바폼 지원자일 경우 상세페이지 API 불러오기 구현 완료 , UI 미완성
  .github/workflows/chromatic.yml
  next.config.mjs
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(home)/page.tsx
  src/app/(pages)/albaFormDetail/applicant/[formId]/page.tsx
  src/app/(pages)/albaFormDetail/layout.tsx
  src/app/(pages)/albaFormDetail/owner/[id]/page.tsx
  src/app/(pages)/albaFormSupportDetail/layout.tsx
  src/app/(pages)/albaFormSupportDetail/page.tsx
  src/app/(pages)/albaList/page.tsx
  src/app/api/oauth/callback/google/route.ts
  src/app/api/oauth/callback/kakao/route.ts
  src/hooks/queries/form/userFormDetail.ts
  src/utils/oauthLoginError.ts
Labels: ✨ Feat, 🎨 Design, 📬 API

#118 feat: 내 알바폼 > 지원자 페이지 추가
  package-lock.json
  package.json
  src/app/(pages)/albaList/page.tsx
  src/app/(pages)/myAlbaform/(role)/applicant/components/ApplicantSortSection.tsx
  src/app/(pages)/myAlbaform/(role)/applicant/page.tsx
  src/app/(pages)/myAlbaform/(role)/owner/page.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/MyApplicationListItem.tsx
  src/app/components/card/cardList/ScrapListItem.tsx
  src/app/stories/design-system/components/card/cardList/MyApplicationListItem.stories.tsx
  src/app/stories/design-system/pages/albaList/page.tsx
  src/types/application.ts
  src/types/response/application.d.ts
Labels: ✨ Feat, 🔨 Refactor, 🎨 Design

#121 feat: kakao-map 테스트 페이지 추가 및 폴더명 수정
  package-lock.json
  package.json
  src/app/(pages)/kakao-map/page.tsx
  src/app/(pages)/myAlbaform/(role)/applicant/page.tsx
  src/app/(pages)/myAlbaform/(role)/owner/page.tsx
  src/app/(pages)/myAlbaform/page.tsx
  src/app/components/layout/Header.tsx
  src/app/stories/design-system/components/layout/Header.tsx
  src/types/kakao.d.ts
  tsconfig.json
Labels: 📦️ Chore, ✨ Feat

#122 Refactor: 알바폼 상세페이지 지원자/사장님 같은 url에서 분기
  src/app/(pages)/alba/[formId]/page.tsx
  src/app/(pages)/alba/components/ApplicationStatus.tsx
  src/app/(pages)/alba/components/FormActions.tsx
  src/app/(pages)/alba/components/FormDetail.tsx
  src/app/(pages)/alba/components/FormHeader.tsx
  src/app/(pages)/alba/components/RecruitInfomation.tsx
  src/app/(pages)/alba/layout.tsx
  src/app/(pages)/albaFormDetail/applicant/[formId]/page.tsx
  src/app/(pages)/albaFormDetail/owner/[id]/page.tsx
  src/app/(pages)/albaList/page.tsx
  src/app/components/button/default/Button.tsx
  src/app/components/card/cardList/ApplicationStatusCard.tsx
  src/app/stories/design-system/components/card/cardList/ApplicationStatusCard.stories.tsx
  src/hooks/queries/form/detail/useApplicationStatus.ts
  src/hooks/queries/form/detail/useFormDetail.ts
Labels: ✨ Feat, 🎨 Style, 📬 API

#120 Feat : alba/edit 알바폼 수정 페이지
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/addform/section/RecruitConditionSection.tsx
  src/app/(pages)/(albaform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(albaform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/page.tsx
  src/app/(pages)/(albaform)/apply/[formId]/page.tsx
  src/app/(pages)/(albaform)/component/Label.tsx
  src/app/(pages)/(albaform)/component/addFormLayout/AddFormLayout.tsx
  src/app/(pages)/(albaform)/component/addFormLayout/ApplyHeader.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/api/forms/[formId]/applications/route.ts
  src/app/api/forms/[formId]/route.ts
  src/app/components/button/dropdown/InputDropdown.tsx
  src/app/components/button/dropdown/TabMenuDropdown.tsx
  src/app/components/card/cardList/ApplicationStatusCard.tsx
  src/app/components/input/dateTimeDaypicker/DatePickerInput.tsx
  src/app/components/input/dateTimeDaypicker/TimePickerInput.tsx
  src/app/components/input/text/LocationInput.tsx
  src/app/stories/design-system/components/card/cardList/RecruitCondition.stories.tsx
  src/app/stories/design-system/components/card/cardList/RecruitDetail.stories.tsx
  src/app/stories/design-system/components/dropdown/TabMenuDropdown.stories.tsx
  src/hooks/queries/form/detail/useFormDetail.ts
  src/hooks/useEditing.ts
  src/types/addform.d.ts
  src/types/response/form.d.ts
  src/utils/formatMoney.ts
Labels: 📬 API

#123 feat: 근무 위치 daum postcode 연동 및 관련 수정 등
  src/app/(home)/page.tsx
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(albaform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/myAlbaform/(role)/owner/page.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/components/input/text/LocationInput.tsx
  src/app/components/modal/modals/confirm/CustomFormModal.tsx
  src/types/modal.d.ts
Labels: 📦️ Chore, ✨ Feat

#124 Fix : 폼 관련 수정
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/page.tsx
  src/app/(pages)/(albaform)/apply/[formId]/page.tsx
  src/app/(pages)/(albaform)/component/ApplyHeader.tsx
  src/app/(pages)/(albaform)/component/addFormLayout/AddFormLayout.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/components/button/dropdown/InputDropdown.tsx
Labels: 📦️ Chore, 🐞 Fix

#128 feat: 알바폼 상세 페이지 kakao map 연동
  src/app/(pages)/alba/[formId]/page.tsx
  src/app/components/modal/modals/confirm/SelectProgressModal.tsx
Labels: 📦️ Chore, ✨ Feat

#132 Refactor : alba/[id] 폴더 병합
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(albaform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/components/ApplicationStatus.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/components/FormActions.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/components/FormDetail.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/components/FormHeader.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/components/RecruitInfomation.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/page.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/(pages)/albax/layout.tsx
  src/app/components/button/default/CheckBtn.tsx
  src/app/components/input/dateTimeDaypicker/DayPickerBtn.tsx
  src/app/components/input/dateTimeDaypicker/DayPickerList.tsx
  src/app/components/input/textarea/BaseTextArea.tsx
  src/app/stories/design-system/components/input/picker/DayPicker.stories.tsx
  src/hooks/useEditing.ts
  src/types/addform.d.ts
Labels: 🔨 Refactor

#133 Refactor : RecruitIcon CSS 수정
  src/app/components/card/cardList/RecruitIcon.tsx
  src/app/components/card/cardList/RecruitIconItem.tsx
  src/utils/workDayFormatter.ts
Labels: 🔨 Refactor, 🎨 Design

#137 Feat: 알바폼 상세 페이지 이미지 수정(수정 중)
  package-lock.json
  public/loding.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/ApplicationStatus.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormActions.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormDetail.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormHeader.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormImage.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/RecruitInformation.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/components/FormActions.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/page.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/(pages)/albaList/layout.tsx
  src/app/(pages)/albaList/page.tsx
  src/app/(pages)/albaTalk/addTalk/page.tsx
  src/app/(pages)/albaform-support-detail/layout.tsx
  src/app/(pages)/albax/layout.tsx
  src/app/(pages)/kakao-map/page.tsx
  src/app/(pages)/myAlbaform/(role)/applicant/page.tsx
  src/app/(pages)/myAlbaform/(role)/owner/page.tsx
  src/app/(pages)/myAlbaform/layout.tsx
  src/app/(pages)/myAlbaform/page.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/mypage/layout.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/RecruitCondition.tsx
  src/app/components/card/cardList/RecruitDetail.tsx
  src/app/components/card/cardList/RecruitIcon.tsx
  src/app/components/card/cardList/ScrapListItem.tsx
  src/app/components/loading-spinner/DotLodingSpinner.tsx
  src/app/components/loading-spinner/LoadingSpinner.tsx
  src/app/components/modal/modals/confirm/DeleteFormModal.tsx
  src/app/components/modal/modals/confirm/SelectProgressModal.tsx
  src/app/components/modal/modals/form/ChangePasswordModal.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/app/stories/design-system/pages/albaList/page.tsx
  src/hooks/queries/auth/useLogin.ts
  src/hooks/queries/auth/useSignup.ts
Labels: 📦️ Chore, ✨ Feat

#134 Feat: 알바 토크 목록, 마이페이지 내가 쓴 글 등
  src/app/(pages)/albaTalk/layout.tsx
  src/app/(pages)/albaTalk/page.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/MyApplicationListItem.tsx
  src/app/components/card/cardList/RecruitIcon.tsx
  src/app/components/card/cardList/ScrapListItem.tsx
  src/app/components/layout/posts/SearchSection.tsx
  src/app/components/layout/posts/SortSection.tsx
  src/app/stories/design-system/components/card/board/BoardComment.stories.tsx
  src/app/stories/design-system/components/card/board/CardBoard.stories.tsx
  src/app/stories/design-system/components/card/board/Comment.stories.tsx
  src/hooks/queries/post/usePosts.ts
  src/utils/dateFormatter.ts
  src/utils/workDayFormatter.ts
Labels: 📦️ Chore, ✨ Feat

#138 design: 사장님 정보 관리 모달 CSS 수정
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
Labels: 🎨 Design

#139 Chore : design 등 자잘한 수정
  src/app/(pages)/albaList/layout.tsx
  src/app/(pages)/albaTalk/layout.tsx
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/layout/Header.tsx
  src/app/components/loading-spinner/LoadingSpinner.tsx
  src/app/not-found.tsx
Labels: 📦️ Chore, 🎨 Design

#140 Chore: 자잘한 수정
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormActions.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormImage.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/RecruitInformation.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/RecruitCondition.tsx
  src/app/components/card/cardList/RecruitIconItem.tsx
  src/app/components/loading-spinner/DotLodingSpinner.tsx
  src/app/components/pagination/Indicator.tsx
  src/utils/checkS3Url.ts
Labels: 📦️ Chore, ✨ Feat

#142 refactor: 마이페이지 정렬 드랍다운 위치 수정 등
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormActions.tsx
  src/app/(pages)/albaList/page.tsx
  src/app/(pages)/albaTalk/[albatalkId]/page.tsx
  src/app/(pages)/albaTalk/addTalk/page.tsx
  src/app/(pages)/albaTalk/page.tsx
  src/app/(pages)/mypage/components/FilterBar/SortSection.tsx
  src/app/(pages)/mypage/components/FilterBar/index.tsx
  src/app/(pages)/mypage/components/MyPageContent.tsx
  src/app/(pages)/mypage/page.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/board/CommentDetail.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/ScrapListItem.tsx
  src/app/components/input/file/ImageInput/ImageInputPlaceHolder.tsx
  src/app/components/loading-spinner/DotLoadingSpinner.tsx
  src/app/components/modal/modals/confirm/DeleteFormModal.tsx
  src/app/components/modal/modals/confirm/SelectProgressModal.tsx
  src/app/components/modal/modals/edit/EditPost.tsx
  src/app/components/modal/modals/form/ChangePasswordModal.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/app/stories/design-system/components/input/image/ImageInputPlaceHolder.stories.tsx
  src/hooks/queries/form/useForms.ts
  src/hooks/queries/post/usePosts.ts
Labels: 📦️ Chore, 🔨 Refactor, 🎨 Design

#145 Fix: 한글 파일 이미지 업로드 이슈 해결 / Refactor : form
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/page.tsx
  src/app/(pages)/(albaform)/apply/[formId]/page.tsx
  src/app/api/(file)/images/upload/route.ts
  src/app/api/forms/[formId]/applications/route.ts
  src/hooks/queries/user/me/useImageUpload.ts
  src/utils/renameFile.ts
  src/utils/tempSave.ts
  src/utils/uploadResume.ts
Labels: 🐞 Fix, 🔨 Refactor

#146 Feat: 알바폼 상세 스크랩(버그있음) / 카카오 공유하기 추가
  next.config.mjs
  src/app/(pages)/(albaform)/alba/[formId]/page.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/components/button/default/BookmarkBtn.tsx
  src/app/components/button/default/ScrapBtn.tsx
  src/app/stories/design-system/components/buttons/BookmarkBtn.stories.tsx
  src/app/stories/design-system/components/buttons/ScrapBtn.stories.tsx
  src/hooks/queries/form/detail/useFormDetail.ts
  src/utils/kakaoShare.ts
Labels: ✨ Feat

#147 refactor: 알바 토크 관련 수정 중
  src/app/(pages)/albaTalk/[albatalkId]/page.tsx
  src/app/(pages)/albaTalk/[albatalkId]/sections/CommentsSection.tsx
  src/app/(pages)/albaTalk/[albatalkId]/sections/PostDetailSection.tsx
  src/app/(pages)/albaTalk/add/page.tsx
  src/app/(pages)/albaTalk/edit/[id]/page.tsx
  src/app/(pages)/albaTalk/page.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/api/forms/[formId]/route.ts
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/card/board/CommentDetail.tsx
  src/app/components/modal/modals/edit/EditPost.tsx
  src/app/stories/design-system/components/card/board/BoardComment.stories.tsx
  src/app/stories/design-system/components/card/board/CardBoard.stories.tsx
  src/app/stories/design-system/components/card/board/Comment.stories.tsx
  src/hooks/queries/post/comment/useAddComment.ts
  src/hooks/queries/post/comment/useComments.ts
  src/hooks/queries/post/comment/useDeleteComment.ts
  src/hooks/queries/post/comment/useEditComment.ts
  src/hooks/queries/post/useAddPost.ts
  src/hooks/queries/post/useDeletePost.ts
  src/hooks/queries/post/useEditPost.ts
  src/hooks/queries/post/useLikePost.ts
  src/hooks/queries/post/usePostDetail.ts
  src/hooks/usePost.ts
  src/hooks/usePostActions.ts
  src/types/post.ts
Labels: 🔨 Refactor

#148 Refactor : 헤더, 모달 CSS 일부 수정
  src/app/(home)/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormDetail.tsx
  src/app/(pages)/kakao-map/page.tsx
  src/app/(pages)/myAlbaform/(role)/owner/page.tsx
  src/app/(pages)/mypage/components/FilterBar/TabMenu.tsx
  src/app/(pages)/mypage/components/FilterBar/index.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/mypage/layout.tsx
  src/app/components/button/default/BookmarkBtn.tsx
  src/app/components/button/default/FloatingBtn.tsx
  src/app/components/button/default/RadioBtn.tsx
  src/app/components/button/dropdown/FilterDropdown.tsx
  src/app/components/button/dropdown/KebabDropdown.tsx
  src/app/components/card/board/CommentDetail.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/ApplicationStatusCard.tsx
  src/app/components/card/cardList/MyApplicationListItem.tsx
  src/app/components/card/cardList/ScrapListItem.tsx
  src/app/components/input/dateTimeDaypicker/DatePickerHeader.tsx
  src/app/components/input/dateTimeDaypicker/DayPickerBtn.tsx
  src/app/components/layout/Header.tsx
  src/app/components/layout/forms/SearchSection.tsx
  src/app/components/loading-spinner/LoadingSpinner.tsx
  src/app/components/modal/ModalLayout.tsx
  src/app/components/modal/modals/alert/ApplicationDetailModal.tsx
  src/app/components/modal/modals/alert/FormContinueModal.tsx
  src/app/components/modal/modals/alert/RecruitmentClosedModal.tsx
  src/app/components/modal/modals/confirm/CustomFormModal.tsx
  src/app/components/modal/modals/confirm/DeleteFormModal.tsx
  src/app/components/modal/modals/confirm/SelectProgressModal.tsx
  src/app/components/modal/modals/form/ChangePasswordModal.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/app/components/popUp/closeButton.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/stories/design-system/components/modal/ModalLayout.stories.tsx
Labels: 📦️ Chore, 🔨 Refactor, 🎨 Design

#151 fix: 무한 스크롤 에러 수정 등
  src/app/(pages)/albaTalk/[albatalkId]/page.tsx
  src/app/(pages)/albaTalk/[albatalkId]/sections/CommentsSection.tsx
  src/app/(pages)/albaTalk/[albatalkId]/sections/PostDetailSection.tsx
  src/app/(pages)/albaTalk/edit/[id]/page.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/input/file/ImageInput/ImageInputPlaceHolder.tsx
  src/app/components/input/textarea/BaseTextArea.tsx
  src/app/components/pagination/Pagination.tsx
  src/app/stories/design-system/components/pagination/Pagination.stories.tsx
  src/hooks/queries/post/comment/useDeleteComment.ts
  src/hooks/queries/user/me/useMyApplications.ts
  src/hooks/queries/user/me/useMyComments.ts
  src/hooks/queries/user/me/useMyForms.ts
  src/hooks/queries/user/me/useMyPosts.ts
  src/hooks/queries/user/me/useMyScraps.ts
Labels: 📦️ Chore, 🐞 Fix, 🔨 Refactor

#153 게시글 상세 UI 수정 등
  src/app/(pages)/(albaform)/apply/[formId]/page.tsx
  src/app/(pages)/albaTalk/[albatalkId]/sections/PostDetailSection.tsx
  src/app/api/posts/[postId]/like/route.ts
  src/app/api/posts/[postId]/route.ts
  src/app/components/card/cardList/MyApplicationListItem.tsx
  src/app/components/input/file/ImageInput/ImageInputPlaceHolder.tsx
  src/app/components/pagination/Pagination.tsx
  src/app/components/pagination/paginationComponent/PaginationBtn.tsx
  src/app/globals.css
  src/hooks/queries/post/useAddPost.ts
  tailwind.config.ts
Labels: 🐞 Fix, 🔨 Refactor, 🎨 Design

#156 Refactor : 알바폼 상세 페이지 layout
  src/app/(pages)/(albaform)/alba/[formId]/components/FormDetail.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormHeader.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/RecruitInformation.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/card/cardList/RecruitIcon.tsx
Labels: 📦️ Chore, 🎨 Design

#157 마이페이지 > 내가 쓴 글, 내가 쓴 댓글 수정
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/components/card/board/BoardComment.tsx
  src/hooks/useWidth.ts
Labels: 🔨 Refactor

#161 Rename : route 경로 이름 변경
  src/app/(home)/page.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormActions.tsx
  src/app/(pages)/(albaform)/apply/[formId]/page.tsx
  src/app/(pages)/alba-list/layout.tsx
  src/app/(pages)/alba-list/page.tsx
  src/app/(pages)/alba-talk/[albatalkId]/edit/page.tsx
  src/app/(pages)/alba-talk/[albatalkId]/page.tsx
  src/app/(pages)/alba-talk/[albatalkId]/sections/CommentsSection.tsx
  src/app/(pages)/alba-talk/[albatalkId]/sections/PostDetailSection.tsx
  src/app/(pages)/alba-talk/add/page.tsx
  src/app/(pages)/alba-talk/layout.tsx
  src/app/(pages)/alba-talk/page.tsx
  src/app/(pages)/my-albaform/(role)/applicant/components/ApplicantSortSection.tsx
  src/app/(pages)/my-albaform/(role)/applicant/page.tsx
  src/app/(pages)/my-albaform/(role)/owner/page.tsx
  src/app/(pages)/my-albaform/layout.tsx
  src/app/(pages)/my-albaform/page.tsx
  src/app/(pages)/my-apply/[formId]/page.tsx
  src/app/(pages)/my-apply/layout.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/layout/Header.tsx
  src/app/stories/design-system/components/layout/Header.tsx
Labels: 📦️ Chore

#163 테스트 계정(지원자, 사장님) 추가 및 자잘한 수정 등
  public/fonts/hakgyo/HakgyoansimDunggeunmisoTTF-B.woff2
  public/fonts/hakgyo/HakgyoansimDunggeunmisoTTF-R.woff2
  public/fonts/nexon/NexonLv1GothicOTF-B.woff
  public/fonts/nexon/NexonLv1GothicOTF-R.woff
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(home)/page.tsx
  src/app/(pages)/mypage/components/FilterBar/index.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/components/button/default/Button.tsx
  src/app/components/button/default/LinkBtn.tsx
  src/app/components/layout/Header.tsx
  src/app/components/layout/forms/SearchSection.tsx
  src/app/components/modal/modals/form/ChangePasswordModal.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/app/fonts.ts
  src/app/globals.css
  src/app/layout.tsx
  src/constants/userRoles.ts
  tailwind.config.ts
Labels: 📦️ Chore, ✨ Feat, 🐞 Fix, 🎨 Style

#164 Refactor : 알바폼 작성/수정 페이지 개선
  src/app/(pages)/(albaform)/addform/page.tsx
  src/app/(pages)/(albaform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/FormDetail.tsx
  src/app/(pages)/(albaform)/alba/[formId]/edit/page.tsx
  src/app/(pages)/(albaform)/component/ApplyHeader.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/components/button/dropdown/FilterDropdown.tsx
  src/app/components/button/dropdown/TabMenuDropdown.tsx
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/components/input/file/ImageInput/PreviewItem.tsx
  src/app/components/input/textarea/BaseTextArea.tsx
  src/types/addform.d.ts
Labels: 🐞 Fix, 🔨 Refactor

#168 bugfix: 스크랩, 카카오 공유 스크립트 초기화, 태블릿 반응형 css 등 수정
  src/app/(pages)/(albaform)/alba/[formId]/components/FormActions.tsx
  src/app/(pages)/(albaform)/alba/[formId]/components/RecruitInformation.tsx
  src/app/(pages)/(albaform)/alba/[formId]/page.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/(pages)/my-albaform/(role)/applicant/page.tsx
  src/app/(pages)/my-apply/[formId]/page.tsx
  src/app/components/button/default/ExpandedFloatingBtn.tsx
  src/app/components/button/default/FloatingBtn.tsx
  src/app/components/button/default/ScrapBtn.tsx
  src/app/components/card/cardList/RecruitIconItem.tsx
  src/utils/kakaoShare.ts
  src/utils/shareToKakao.ts
Labels: 🐞 Fix

#175 사장님 관련 마이페이지 스크랩 제거 등
  src/app/(auth)/login/page.tsx
  src/app/(pages)/(albaform)/layout.tsx
  src/app/(pages)/alba-list/page.tsx
  src/app/(pages)/alba-talk/[albatalkId]/sections/PostDetailSection.tsx
  src/app/(pages)/alba-talk/page.tsx
  src/app/(pages)/mypage/components/FilterBar/SortSection.tsx
  src/app/(pages)/mypage/components/FilterBar/TabMenu.tsx
  src/app/(pages)/mypage/components/FilterBar/constants.ts
  src/app/(pages)/mypage/page.tsx
  src/app/components/button/default/Button.tsx
  src/app/components/button/default/LinkBtn.tsx
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/layout/Header.tsx
  src/app/components/layout/forms/SearchSection.tsx
  src/app/components/layout/forms/SortSection.tsx
  src/app/components/layout/posts/SortSection.tsx
  src/app/components/modal/modals/confirm/CustomFormModal.tsx
  src/hooks/queries/post/comment/useAddComment.ts
  src/hooks/queries/post/comment/useDeleteComment.ts
  src/hooks/queries/post/comment/useEditComment.ts
  src/hooks/queries/post/useAddPost.ts
  src/hooks/queries/post/useDeletePost.ts
  src/hooks/queries/post/useEditPost.ts
Labels: 📦️ Chore

#177 chore: 파비콘 수정
  public/android-icon-192x192.png
  public/apple-icon-180x180.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/favicon.svg
  public/site.webmanifest
  src/app/components/layout/Header.tsx
Labels: 📦️ Chore, 🎨 Design

#181 design: 사이드바 수정
  src/app/components/button/default/LinkBtn.tsx
  src/app/components/layout/Header.tsx
Labels: 🎨 Design

#182 design: 사이드바 다시 수정
  src/app/(pages)/work-talk/[talkId]/edit/page.tsx
  src/app/(pages)/work-talk/[talkId]/page.tsx
  src/app/(pages)/work-talk/[talkId]/sections/CommentsSection.tsx
  src/app/(pages)/work-talk/[talkId]/sections/PostDetailSection.tsx
  src/app/components/button/default/LinkBtn.tsx
  src/app/components/layout/Header.tsx
Labels: 🎨 Design

#183 chore: 자잘한 수정
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/(pages)/my-workform/(role)/applicant/page.tsx
  src/app/(pages)/my-workform/(role)/owner/page.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/work-list/page.tsx
  src/app/(pages)/work-talk/page.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/layout/forms/SearchSection.tsx
  src/app/components/loading-spinner/NoApplySpinner.tsx
  src/app/components/loading-spinner/SearchSpinner.tsx
Labels: 📦️ Chore

#187 fix: 워크톡 > 상세 id 관련 버그 수정
  src/app/(pages)/work-talk/[talkId]/page.tsx
Labels: 🐞 Fix

#188 Feat: 회원의 내 지원내역 조회
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/(pages)/my-apply/[formId]/page.tsx
  src/app/(pages)/my-apply/layout.tsx
  src/app/(pages)/my-workform/(role)/applicant/page.tsx
  src/app/api/forms/[formId]/applications/my-apply/route.ts
  src/app/api/forms/[formId]/applications/my-apply/verify/route.ts
  src/app/components/button/default/FloatingBtn.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/MyApplicationListItem.tsx
  src/app/components/card/cardList/apply/ApplyStatusCard.tsx
  src/app/components/card/cardList/apply/MyApplicationListItem.tsx
  src/app/components/modal/ModalLayout.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/components/modal/modals/confirm/SelectProgressModal.tsx
  src/app/stories/design-system/components/card/cardList/MyApplicationListItem.stories.tsx
  src/hooks/queries/user/me/UseApplicationsList.ts
  src/hooks/queries/user/me/useMyApplication.ts
  src/types/applicationStatus.ts
  src/types/modal.d.ts
  src/types/response/application.d.ts
  src/utils/translateStatus.ts
Labels: ✨ Feat

#189 refactor: 로그인, 회원가입 AuthInput 추가 및 사용 등
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(pages)/(workform)/work/[formId]/edit/page.tsx
  src/app/components/input/text/AuthInput.tsx
  src/types/textInput.d.ts
Labels: 🔨 Refactor

#190 feat: 무한스크롤 있는 페이지에 최상단으로 스크롤 되는 버튼 추가
  src/app/(pages)/my-workform/(role)/applicant/page.tsx
  src/app/(pages)/my-workform/(role)/owner/page.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/work-list/page.tsx
  src/app/(pages)/work-talk/page.tsx
  src/app/components/button/default/ScrollTopButton.tsx
Labels: ✨ Feat

#191 Refactor : 리액트 훅폼 외 기타 수정
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/(layout)/applicant/page.tsx
  src/app/(auth)/signup/(layout)/component/Background.tsx
  src/app/(auth)/signup/(layout)/layout.tsx
  src/app/(auth)/signup/(layout)/owner/page.tsx
  src/app/(auth)/signup/applicant/page.tsx
  src/app/(auth)/signup/owner/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/addform/section/RecruitConditionSection.tsx
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(workform)/apply/[formId]/page.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/(pages)/(workform)/work/[formId]/edit/page.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/work-list/page.tsx
  src/app/(pages)/work-talk/[talkId]/sections/CommentsSection.tsx
  src/app/components/button/default/Button.tsx
  src/app/components/button/default/ScrapBtn.tsx
  src/app/components/button/dropdown/TabMenuDropdown.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/EmptyImage.tsx
  src/app/components/card/cardList/InfoItem.tsx
  src/app/components/input/dateTimeDaypicker/DatePickerInput.tsx
  src/app/components/loading-spinner/LoadingSpinner.tsx
  src/app/components/pagination/paginationComponent/PaginationBtn.tsx
  src/app/globals.css
  src/app/stories/design-system/components/input/picker/DatePicker.stories.tsx
  src/app/stories/design-system/components/layout/Header.tsx
  src/utils/tempSave.ts
Labels: 📦️ Chore, 🔨 Refactor

#192 Feat: 회원의 myapply 이력서 다운로드 추가
  package-lock.json
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/(pages)/my-workform/(role)/applicant/page.tsx
  src/app/components/card/cardList/apply/MyApplicationListItem.tsx
  src/app/components/layout/ContentSection.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/stories/design-system/components/card/cardList/SubmitContCard.stories.tsx
  src/hooks/queries/user/me/useApplicationsList.ts
  src/hooks/useResumeDownLoad.tsx
  src/types/modal.d.ts
  src/types/response/application.d.ts
Labels: 📦️ Chore, ✨ Feat

#193 chore : 추가 수정
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(workform)/work/[formId]/edit/page.tsx
  src/hooks/queries/user/me/useImageUpload.ts
  src/hooks/queries/user/me/useUpdateProfile.ts
Labels: 📦️ Chore

#194 Feat: css 자잘한 수정
  public/images/applicant.png
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/work-talk/[talkId]/sections/PostDetailSection.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/layout/Header.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/hooks/queries/post/useLikePost.ts
Labels: 📦️ Chore

#202 SEO 관련 .env 설정 추가 metadata, layout 수정 등
  public/images/workroot_home.png
  src/app/layout.tsx
  src/app/metadata.ts
  src/utils/workDayFormatter.ts
Labels: ✨ Feat, 🐞 Fix

#203 내 워크폼 > 사장님 카드 아이템 수정하기, 삭제하기 케밥 드롭다운 추가
  public/og-image.png
  public/site.webmanifest
  src/app/(home)/page.tsx
  src/app/(pages)/(workform)/work/[formId]/edit/page.tsx
  src/app/(pages)/my-workform/(role)/owner/page.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/hooks/queries/form/useDeleteForm.ts
Labels: 🐞 Fix, 🔨 Refactor

#204 Refactor : 이력서 로직 수정 / Fix: 자잘한 버그 수정
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(workform)/apply/[formId]/page.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/(pages)/(workform)/work/[formId]/edit/page.tsx
  src/app/components/card/cardList/apply/MyApplicationListItem.tsx
  src/app/components/layout/Header.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/types/addform.d.ts
  src/utils/uploadResume.ts
Labels: 🐞 Fix, 🔨 Refactor

#209 Refactor: 색상 테마 변경
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/(layout)/applicant/page.tsx
  src/app/(auth)/signup/(layout)/component/Background.tsx
  src/app/(auth)/signup/(layout)/owner/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(home)/page.tsx
  src/app/components/button/default/Button.tsx
  src/app/components/button/default/LinkBtn.tsx
  src/app/components/input/text/AuthInput.tsx
  src/app/components/layout/Header.tsx
  src/app/components/layout/forms/SearchSection.tsx
  src/app/components/modal/modals/form/ChangePasswordModal.tsx
  src/app/components/modal/modals/form/EditMyProfileModal.tsx
  src/app/components/modal/modals/form/EditOwnerProfileModal.tsx
  src/app/globals.css
  src/app/stories/design-system/components/layout/Header.tsx
  tailwind.config.ts
Labels: 🎨 Design

#210 Refactor : 지원하기 페이지 수정
  package.json
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(workform)/apply/[formId]/page.tsx
  src/app/(pages)/(workform)/layout.tsx
  src/app/(pages)/(workform)/work/[formId]/edit/page.tsx
  src/app/(pages)/(workform)/work/[formId]/page.tsx
  src/app/(pages)/my-workform/(role)/applicant/page.tsx
  src/app/(pages)/my-workform/(role)/owner/page.tsx
  src/app/(pages)/my-workform/layout.tsx
  src/app/(pages)/my-workform/page.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/work-list/layout.tsx
  src/app/(pages)/work-list/page.tsx
  src/app/(pages)/work-talk/[talkId]/edit/page.tsx
  src/app/(pages)/work-talk/[talkId]/sections/CommentsSection.tsx
  src/app/(pages)/work-talk/layout.tsx
  src/app/(pages)/work-talk/page.tsx
  src/app/api/(file)/resume/upload/route.ts
  src/app/components/button/default/Button.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/cardList/apply/MyApplicationListItem.tsx
  src/app/stories/design-system/pages/albaList/page.tsx
Labels: 📦️ Chore, 🔨 Refactor

#212 refactor: 워크폼 상세페이지에 카카오톡 공유하기 페이지 별로 공유 컨텐츠 설정
  next-sitemap.config.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  src/app/(pages)/(workform)/work/[formId]/components/RecruitInformation.tsx
  src/app/(pages)/(workform)/work/[formId]/page.tsx
  src/app/(pages)/work-list/page.tsx
  src/app/components/button/default/ExpandedFloatingBtn.tsx
  src/utils/shareToKakao.ts
Labels: 🔨 Refactor

#216 refactor: SEO 관련 설정 수정 등
  .gitignore
  next-sitemap.config.js
  public/naverefadbf91c571363d3fa278513c5cc117.html
  public/sitemap-0.xml
  public/sitemap.xml
  src/app/(pages)/kakao-map/page.tsx
  src/app/api/forms/[formId]/route.ts
  src/app/api/forms/route.ts
  src/app/components/input/text/LocationInput.tsx
  src/app/layout.tsx
  src/app/metadata.ts
Labels: 🔨 Refactor

#219 페이스북 app_id 관련 수정 등
  src/app/metadata.ts
  src/app/viewport.ts
Labels: 🐞 Fix

#218 design: 브랜드 로고 이미지 추가
  public/black_brand_logo.png
  public/black_icon_logo.png
  public/black_main_logo.png
  public/black_text_logo.png
  src/app/components/layout/Header.tsx
Labels: 🎨 Design

#221 Refactor : 마이페이지 design / Fix: 달력 초기화 안되는 문제
  public/icons/document/document.svg
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/addform/section/RecruitConditionSection.tsx
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(workform)/work/[formId]/page.tsx
  src/app/(pages)/my-workform/(role)/applicant/page.tsx
  src/app/(pages)/my-workform/(role)/owner/page.tsx
  src/app/(pages)/mypage/components/FilterBar/TabMenu.tsx
  src/app/(pages)/mypage/components/FilterBar/index.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/mypage/layout.tsx
  src/app/(pages)/work-list/page.tsx
  src/app/(pages)/work-talk/page.tsx
  src/app/api/(file)/resume/upload/route.ts
  src/app/components/button/dropdown/KebabDropdown.tsx
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/BoardPostItem.tsx
  src/app/components/card/cardList/RecruitCondition.tsx
  src/app/components/card/cardList/ScrapListItem.tsx
  src/app/components/input/dateTimeDaypicker/DatePickerInput.tsx
  src/app/components/layout/ContentSection.tsx
  src/app/stories/design-system/components/card/cardList/BoardCommentItem.stories.tsx
  src/app/stories/design-system/components/card/cardList/BoardPostItem.stories.tsx
  src/app/stories/design-system/components/card/cardList/ScapListItem.stories.tsx
  src/images/logo.svg
Labels: 🐞 Fix, 🎨 Design

#222 페이스북 SEO 관련 수정
  src/app/api/forms/[formId]/route.ts
  src/app/layout.tsx
  src/app/metadata.ts
Labels: 🐞 Fix

#224 chore: 자잘한 수정
  src/app/(pages)/(workform)/work/[formId]/components/RecruitInformation.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/components/modal/modals/apply/VerifyApplicationModal.tsx
  src/hooks/queries/user/me/useGuestApplication.ts
Labels: 📦️ Chore

#225 feat: 마우스 커서 트레일 추가
  package-lock.json
  package.json
  src/app/components/layout/Header.tsx
  src/app/components/mouseTrail/CustomCursor.tsx
  src/app/components/mouseTrail/MouseTrail.tsx
  src/app/globals.css
  src/app/layout.tsx
Labels: 🎨 Design

#227 feat: 랜딩페이지 수정(미완)
  package-lock.json
  package.json
  public/images/land/s2.webp
  src/app/(home)/page.tsx
Labels: 🎨 Design

#229 Chore: 헤더 로딩 스피너 변경
  package-lock.json
  src/app/(home)/page.tsx
  src/app/components/layout/Header.tsx
  src/app/components/loading-spinner/HamburgerSpinner.tsx
  src/app/components/loading-spinner/Spinner.css
Labels: 📦️ Chore, 🎨 Design

#231 Feat: 지원현황 업데이트 기능 구현, 이미지 dnd 추가 / chore: 콘솔 경고 개선, 알바폼 작성 이미지 여러개 업로드
  .storybook/main.ts
  package-lock.json
  package.json
  public/favicon.svg
  src/app/(home)/page.tsx
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormImage.tsx
  src/app/clientLayout.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/apply/ApplyStatusCard.tsx
  src/app/components/card/cardList/apply/SkeletonRow.tsx
  src/app/components/card/cardList/apply/TableHeader.tsx
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/components/layout/Header.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/components/modal/modals/confirm/SelectProgressModal.tsx
  src/app/components/mouseTrail/MouseTrail.tsx
  src/app/stories/design-system/components/card/cardList/MyApplicationListItem.stories.tsx
  src/app/stories/design-system/components/input/image/ImageInput.stories.tsx
  src/hooks/queries/form/detail/useApplicationStatus.ts
  src/hooks/queries/form/detail/useUpdateApplicationStatus.ts
  src/hooks/useApplyCard.ts
  src/types/applicationStatus.ts
  src/types/modal.d.ts
  src/utils/translateStatus.ts
Labels: ✨ Feat

#232 chore: 달력 자잘한 수정, 커서 위치 수정, 검색 중 로딩스피너 추가
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/(workform)/addform/section/WorkConditionSection.tsx
  src/app/(pages)/my-workform/(role)/applicant/page.tsx
  src/app/(pages)/my-workform/(role)/owner/page.tsx
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/work-list/page.tsx
  src/app/(pages)/work-talk/page.tsx
  src/app/components/input/dateTimeDaypicker/DatePickerInput.tsx
  src/app/components/layout/Header.tsx
  src/app/components/loading-spinner/HamburgerSpinner.tsx
  src/app/components/loading-spinner/SearchSpinner.tsx
  src/app/components/loading-spinner/SmallLoadingSpinner.tsx
  src/app/components/mouseTrail/CustomCursor.tsx
  src/app/globals.css
  src/app/metadata.ts
  src/app/stories/design-system/pages/albaList/page.tsx
Labels: 📦️ Chore, 🐞 Fix

#233 chore: 커서 수정 / 워크폼 수정 페이지 수정
  src/app/(pages)/(workform)/work/[formId]/edit/page.tsx
  src/app/components/mouseTrail/CustomCursor.tsx
  src/app/components/mouseTrail/MouseTrail.tsx
Labels: 📦️ Chore

#236 fix: 스토리북 커서 안나오는 문제 해결
  .storybook/preview.tsx
  .storybook/storybook.css
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/stories/design-system/components/input/picker/DatePicker.stories.tsx
Labels: 🐞 Fix

#235 ChannelTalk 연동 추가
  package-lock.json
  package.json
  public/sitemap.xml
  src/app/clientLayout.tsx
  src/app/components/layout/ChannelTalk.tsx
Labels: ✨ Feat

#239 fix: 삭제된 ImageInput 컴포넌트 복구
  public/sitemap.xml
  src/app/components/input/file/ImageInput/ImageInput.tsx
Labels: 🐞 Fix

#242 Fix : 워크톡 관련 수정
  package-lock.json
  src/app/(home)/page.tsx
  src/app/(pages)/work-talk/[talkId]/edit/page.tsx
  src/app/(pages)/work-talk/[talkId]/sections/CommentsSection.tsx
  src/app/(pages)/work-talk/[talkId]/sections/PostDetailSection.tsx
  src/app/(pages)/work-talk/add/page.tsx
  src/app/(pages)/work-talk/page.tsx
  src/app/components/animation/TypewriterText.tsx
  src/app/components/card/board/CardBoard.tsx
  src/app/components/card/board/Comment.tsx
  src/app/components/input/file/ImageInput/ImageInputPlaceHolder.tsx
  src/app/layout.tsx
  src/app/stories/design-system/components/input/picker/DayPicker.stories.tsx
Labels: 📦️ Chore

#244 구글 애널리틱스 설정 추가 등
  package-lock.json
  package.json
  public/sitemap.xml
  src/app/(home)/page.tsx
  src/app/(pages)/(workform)/apply/[formId]/page.tsx
  src/app/layout.tsx
Labels: 📦️ Chore, 🐞 Fix

#246 chore: 내가 쓴글 케밥 추가
  src/app/(pages)/mypage/components/sections/CommentsSection.tsx
  src/app/(pages)/mypage/components/sections/PostsSection.tsx
  src/app/(pages)/mypage/page.tsx
  src/app/components/button/dropdown/KebabDropdown.tsx
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/BoardPostItem.tsx
  src/app/components/card/cardList/AlbaListItem.tsx
  src/app/components/card/cardList/apply/MyApplicationListItem.tsx
  src/app/stories/design-system/components/card/cardList/BoardPostItem.stories.tsx
Labels: 📦️ Chore

#248 sitemap.xml 트랙킹 제거
  public/sitemap.xml
Labels: 🐞 Fix

#250 워크톡 @hello-pangea/dnd 로 dnd 교체, 이미지 3개 등록 및 프리뷰 dnd 적용 등
  README.md
  package-lock.json
  package.json
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/work-talk/[talkId]/edit/page.tsx
  src/app/(pages)/work-talk/[talkId]/sections/PostDetailSection.tsx
  src/app/(pages)/work-talk/add/page.tsx
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/hooks/queries/post/useLikePost.ts
Labels: 🔨 Refactor

#251 chore: 지원 내역 모달에서 이력서 다운로드 스피너 추가
  src/app/components/layout/auth/Background.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/hooks/useResumeDownLoad.tsx
Labels: 📦️ Chore

#252 12/26 12시 배포
  README.md
  package-lock.json
  package.json
  public/images/land/s2.jpg
  public/images/land/s2.json
  public/images/land/s2.png
  public/images/land/s3.jpg
  public/images/land/s3.json
  public/images/land/s3.png
  public/images/land/s4.jpg
  public/images/land/s4.png
  public/images/land/step1.jpg
  public/images/land/step1.png
  public/images/land/step2-1.jpg
  public/images/land/step2-1.png
  public/images/land/step2-2.jpg
  public/images/land/step2-2.png
  public/images/land/step3-1.jpg
  public/images/land/step3-1.json
  public/images/land/step3-1.png
  public/images/land/step3-2.jpg
  public/images/land/step3-2.json
  public/images/land/step3-2.png
  public/og-image.png
  public/sitemap.xml
  src/app/(auth)/signup/page.tsx
  src/app/(home)/page.tsx
  src/app/(pages)/(workform)/addform/page.tsx
  src/app/(pages)/(workform)/addform/section/RecruitContentSection.tsx
  src/app/(pages)/work-talk/[talkId]/edit/page.tsx
  src/app/(pages)/work-talk/[talkId]/sections/PostDetailSection.tsx
  src/app/(pages)/work-talk/add/page.tsx
  src/app/components/animation/LeafAnimation.tsx
  src/app/components/button/dropdown/FilterDropdown.tsx
  src/app/components/button/dropdown/dropdownComponent/DropdownList.tsx
  src/app/components/chip/Chip.tsx
  src/app/components/input/file/ImageInput/ImageInput.tsx
  src/app/components/layout/Header.tsx
  src/app/components/layout/auth/Background.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/layout.tsx
  src/hooks/queries/post/useLikePost.ts
  src/hooks/useResumeDownLoad.tsx
  tailwind.config.ts
Labels: 🌎 Deploy

#253 fix: 빌드 프리티어 에러 수정
  src/app/(auth)/signup/page.tsx
  src/app/components/button/dropdown/dropdownComponent/DropdownList.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
Labels: 🐞 Fix

#257 랜딩 페이지 헤더 관련 수정 등
  README.md
  package-lock.json
  package.json
  public/og-image.png
  src/app/(home)/page.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormImage.tsx
  src/app/clientLayout.tsx
  src/app/components/input/text/LocationInput.tsx
  src/app/layout.tsx
Labels: 📦️ Chore, 🎨 Design

#258 12/26 5시 배포
  README.md
  package-lock.json
  package.json
  public/og-image.png
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(home)/page.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormImage.tsx
  src/app/clientLayout.tsx
  src/app/components/button/default/Button.tsx
  src/app/components/input/text/LocationInput.tsx
  src/app/components/layout/Header.tsx
  src/app/components/layout/auth/Background.tsx
  src/app/layout.tsx
  tailwind.config.ts
Labels: 🌎 Deploy

#259 chore: 사장님 회원가입 밑에 SNS 계정 로그인 텍스트 삭제
  src/app/(auth)/signup/(layout)/owner/page.tsx
Labels: 📦️ Chore

#261 fix: 마이페이지 > 내가 쓴 글, 내가 쓴 댓글 케밥 드롭다운 버그 수정 등
  src/app/(pages)/mypage/page.tsx
  src/app/components/card/board/BoardComment.tsx
  src/app/components/card/board/BoardPostItem.tsx
Labels: 🐞 Fix

#264 design: css 수정
  src/app/(pages)/(workform)/apply/[formId]/page.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/clientLayout.tsx
  src/app/components/button/default/ScrapBtn.tsx
  src/app/components/card/cardList/apply/ApplyStatusCard.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/components/mouseTrail/CustomCursor.tsx
Labels: 📦️ Chore

#263 logo.svg 를 logo.png 로 변경
  src/utils/shareToKakao.ts
Labels: 🐞 Fix

#265 최종 발표 전 배포
  src/app/(pages)/(workform)/apply/[formId]/page.tsx
  src/app/(pages)/(workform)/work/[formId]/components/FormActions.tsx
  src/app/clientLayout.tsx
  src/app/components/button/default/ScrapBtn.tsx
  src/app/components/card/cardList/apply/ApplyStatusCard.tsx
  src/app/components/modal/modals/apply/MyApplicationModal.tsx
  src/app/components/mouseTrail/CustomCursor.tsx
  src/utils/shareToKakao.ts
Labels: 🌎 Deploy

#266 Chore : 마이페이지 스크랩 섹션 / 워크톡 작성 페이지 design fix
  src/app/(pages)/mypage/components/sections/ScrapsSection.tsx
  src/app/(pages)/work-talk/[talkId]/edit/page.tsx
  src/app/(pages)/work-talk/add/page.tsx
Labels: 📦️ Chore
